### ISSUE TITLE
サイドメニューのリンクがうまくいかない　修正する

### ISSUE THREAD

**Issue by youdoumei** [youdoumei/coffee_diary#46]
再現手順
・サイドメニューで投稿メニューをクリック。そのあと、投稿一覧メニューをクリックする。
http://localhost:3000/entries/new
⇒
http://localhost:3000/entries/entries
となりエラー
ActiveRecord::RecordNotFound in EntriesController#show
Couldn't find Entry with 'id'=entries

**Comment by youdoumei** [comment]
#56

**Comment by teppeita** [comment]
コメント1件
